Program lermedia;
var
nota1,nota2,nota3,media: real;
begin
     writeln('Infomre a primeira nota');
                      readln(nota1);
     writeln('Informe a segunda nota');
                      readln(nota2);
     writeln('Informe a terceira nota');
                      readln(nota3);
     media:=(nota1+nota2+nota3)/3;
     writeln('Sua media foi:',media);
                  readln(media);
end.