Program lernota;
var
n1,n2,n3,n4, soma: integer;
begin;
      writeln('Infomre a primeira nota');
                       readln(n1);
      writeln('Informe a segunda nota');
                        readln(n2);
      writeln('Informe a terceira nota');
                       readln(n3);
      writeln('Informe a quarta nota');
                       readln(n4);
      soma:=n1+n2+n3+n4;
      writeln('A soma geral foi:',soma);
end.